### ISSUE TITLE
Add mute and volume control to stream

### ISSUE THREAD

**Issue by soul4rent** [PaintWithBob/paint-with-bob#113]

**Comment by soul4rent** [comment]
https://superuser.com/questions/268985/remove-audio-from-video-file-with-ffmpeg

Dumb question: is it possible to add flags after running the video, or would the video have to be restarted?
@torch2424

**Comment by torch2424** [comment]
Oh you are thinking too much into it haha!

Google flv.js, and see how you can mute / change volume on the video player :)

**Comment by torch2424** [comment]
https://stackoverflow.com/questions/14161516/html5-video-completely-hide-controls?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

And just add `controls` to the video element html
