### ISSUE TITLE
Authorization Token In Request Body

### ISSUE THREAD

**Issue by JoshuaWarejko** [PaintWithBob/paint-with-bob#63]
We should switch to sending the token in the Authorization header instead of the request body for all routes. This would required changes on the frontend and backend.

**Comment by JoshuaWarejko** [comment]
This has been resolved by #68

**Comment by torch2424** [comment]
@JoshuaWarejko Just as a heads up, there are special words you can put in PRs to automatically close issues 

https://help.github.com/articles/closing-issues-using-keywords/

So like in your PR you can put `closes #63`, and when it gets merged, github will do this for you :)
