### ISSUE TITLE
"Paint Now" / Guest Join/Create Lobby Does not Work

### ISSUE THREAD

**Issue by torch2424** [PaintWithBob/paint-with-bob#86]
The Paint now button on the homepage does nothing.

We need to finish guests joining or creating random lobbies.

<img width="120" alt="screen shot 2018-03-19 at 4 14 44 pm" src="https://user-images.githubusercontent.com/1448289/37627221-b35f6d3e-2b90-11e8-87cf-e75ce33d25ba.png">

**Comment by torch2424** [comment]
Duplicate of #84

**Comment by JoshuaWarejko** [comment]
Closing because duplicate of #84
