### ISSUE TITLE
Look into putting all of paint with bob on another server

### ISSUE THREAD

**Issue by torch2424** [PaintWithBob/paint-with-bob#99]
I got $50 of linode credit. May be worth throwing paint with bob on that for a cool minute till one of us adopts it

**Comment by torch2424** [comment]
Or, anyone who would be so kind to get the github education pack, get your DO credit, and then they can host it for free for a cool minute. And now DO supports adding other users to your "team", so we can all have DO access to the server and things :)

**Comment by soul4rent** [comment]
"We'll just forever host it. Probably. Maybe."

- @torch2424
